config/routes.rb
SocialStockTicker::Application.routes.draw do
 
  devise_for :admins
  unauthenticated do
    as :admin do
      root :to => 'authentications#index'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :examples, 
                :only => [:index, :create, :show, :update, :destroy], 
                :defaults => { :format => 'json' }
      resources :stocks, 
                :only => [:index, :create, :show, :destroy], 
                :defaults => { :format => 'json' }
    end
  end
  
  namespace :public do
    namespace :v1 do
      resources :stocks, 
                :only => [:index],
                :defaults => { :format => 'json' }
    end
  end
  
  resources :authentications, :only => [:index]
  resources :docs, :only => [:index]
  resources :social_stocks, :only => [:index]

  match "social_stocks_path" => "social_stocks#index"
  root :to => 'social_stocks#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application/_navigation.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
			</a>
			<a class="brand" href=<%="#{root_path}"%> alt="Social Stock Ticker">SocialStockTicker</a>
			<div class="nav-collapse">
				<ul class="nav">
					<% if (request.path == root_path) %>
						<li class="active">
							<a class="test_class" href=<%="#{root_path}"%>>Home</a>
						</li>
					<% else %>
						<li  class="">
							<a class="test_class" href=<%="#{root_path}"%>>Home</a>
						</li>
					<% end %>
					<% if (request.path == docs_path) %>
						<li  class="active">
							<a href=<%="#{docs_path}"%>>Docs</a>
						</li>
					<% else %>
						<li  class="">
							<a href=<%="#{docs_path}"%>>Docs</a>
						</li>
					<% end %>
				</ul>
				<% if (admin_signed_in?) %>
					<ul class="nav pull-right">
						<li>
							<div>
								<%= link_to "Logout", :destroy_admin_session, :method => :delete, :class => "btn btn-success btn-large" %>
							</div>
						</li>
					</ul>
				<% end %>
			</div>
		</div>
	</div>
</div>	